export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const GET_DRIVER_INFORMATION = "GET_DRIVER_INFORMATION";
export const GET_DRIVER_LOCATION = "GET_DRIVER_LOCATION";
export const GET_DISTANCE_FROM_DRIVER = "GET_DISTANCE_FROM_DRIVER";